---
# tasks file for create-droplet

- name: "ensure ssh key exists or generate"
  user: >
    name={{ ansible_user_id }}
    generate_ssh_key=yes
    ssh_key_file=.ssh/id_rsa

- name: "ensure key exists at DigitalOcean"
  digital_ocean: >
    state=present
    command=ssh
    name={{ ssh_key_name }}
    ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
    api_token={{ do_token }}
  register: ssh_key

- name: "Create new droplet"
  digital_ocean: >
    state=present
    command=droplet
    name={{ droplet_name }}
    size_id={{ droplet_size_id }}
    region_id={{ droplet_region_id }}
    image_id={{ droplet_image_id }}
    ssh_key_ids={{ ssh_key.ssh_key.id }}
    api_token={{ do_token }}
  register: droplet


- name: "Print IP Address"
  debug: >
    msg="IP is {{ droplet.droplet.ip_address }}"

- name: "Create new entry in hosts file"
  action: >
    lineinfile dest=./hosts
    line="{{ droplet_name }} ansible_host={{ droplet.droplet.ip_address }}"
    state=present

- name: "Wait for Server to come back"
  local_action: >
    wait_for host={{ droplet.droplet.ip_address }}
    port=22
    state=started
    delay=15
